export const countriesData = [
  { country: 'США', capital: 'Вашингтон' },
  { country: 'Канада', capital: 'Оттава' },
  { country: 'Австралия', capital: 'Канберра' },
  { country: 'Аргентина', capital: 'Буэнос-Айрес' },
  { country: 'Алжир', capital: 'Алжир' },
  { country: 'Австрия', capital: 'Вена' },
  { country: 'Бразилия', capital: 'Бразилиа' },
  { country: 'Германия', capital: 'Берлин' },
  { country: 'Франция', capital: 'Париж' },
  { country: 'Испания', capital: 'Мадрид' },
  { country: 'Италия', capital: 'Рим' },
  { country: 'Япония', capital: 'Токио' },
  { country: 'Китай', capital: 'Пекин' },
  { country: 'Индия', capital: 'Нью-Дели' },
  { country: 'Мексика', capital: 'Мехико' },
  { country: 'Нигерия', capital: 'Абуджа' },
  { country: 'Южная Африка', capital: 'Претория' },
  { country: 'Египет', capital: 'Каир' },
  { country: 'Швеция', capital: 'Стокгольм' },
  { country: 'Норвегия', capital: 'Осло' },
];