export const countriesData = [
  { country: 'США', capital: 'Вашингтон', continent: 'Северная Америка' },
  { country: 'Канада', capital: 'Оттава', continent: 'Северная Америка' },
  { country: 'Австралия', capital: 'Канберра', continent: 'Австралия' },
  { country: 'Аргентина', capital: 'Буэнос-Айрес', continent: 'Южная Америка' },
  { country: 'Алжир', capital: 'Алжир', continent: 'Африка' },
  { country: 'Австрия', capital: 'Вена', continent: 'Европа' },
  { country: 'Бразилия', capital: 'Бразилиа', continent: 'Южная Америка' },
  { country: 'Германия', capital: 'Берлин', continent: 'Европа' },
  { country: 'Франция', capital: 'Париж', continent: 'Европа' },
  { country: 'Испания', capital: 'Мадрид', continent: 'Европа' },
  { country: 'Италия', capital: 'Рим', continent: 'Европа' },
  { country: 'Япония', capital: 'Токио', continent: 'Азия' },
  { country: 'Китай', capital: 'Пекин', continent: 'Азия' },
  { country: 'Индия', capital: 'Нью-Дели', continent: 'Азия' },
  { country: 'Мексика', capital: 'Мехико', continent: 'Северная Америка' },
  { country: 'Нигерия', capital: 'Абуджа', continent: 'Африка' },
  { country: 'Южная Африка', capital: 'Претория', continent: 'Африка' },
  { country: 'Египет', capital: 'Каир', continent: 'Африка' },
  { country: 'Швеция', capital: 'Стокгольм', continent: 'Европа' },
  { country: 'Норвегия', capital: 'Осло', continent: 'Европа' },
];
